name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  integration:
    name: Integration
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
      - run: pnpm install --frozen-lockfile

      - run: pnpm format:check
      - run: pnpm typecheck
      - run: pnpm lint

      - run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Error: There are uncommitted changes after running checks"
            git status --porcelain
            exit 1
          fi
